### ISSUE TITLE
Laravel DI in controller constructor

### ISSUE THREAD

**Issue by a-komarev** [mpociot/botman#112]
I've tried to use interface in constructor, but was faced an issue that it couldn't be instantiated.

This wouldn't work:
```php
public function __construct(ExampleInterface $example)
{
    dd($example);
}
```

This works:
```php
public function __construct()
{
    $example = app(ExampleInterface::class);
    dd($example);
}
```

Any ideas how to solve it without vendor lock?

**Comment by mpociot** [comment]
I assume you are using the `hears` command in combination with the 'Controller@method' syntax?

This will not work because BotMan only uses `call_user_func_array` with the class and method name.

https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L206-L207

As BotMan tries to be as framework independent as possible, this can not be achieved otherwise I guess.
Maybe this can somehow be done in the [botman-laravel-starter](https://github.com/mpociot/botman-laravel-starter) package?

**Comment by a-komarev** [comment]
@mpociot I just thought about ability to set somehow strategy of building controller classes. If not set - use default. This will give an ability to extend it for any framework I suppose.
