### ISSUE TITLE
Botman websocket

### ISSUE THREAD

**Issue by rgr** [mpociot/botman#1158]
- BotMan Version: 2.6.0
- PHP Version: 7.4
- Messaging Service(s): web driver
- Cache Driver: file

### Description:
Hi there,
I'm planning on using the webdriver to link laravel to a flutter app and I don't understand how botman can issue messages on its own via http to the app (only reply to one message with one message). I thought websockets would come to the rescue and I saw a lot of posts here and there from @mpociot about websockets but I can't find anywhere information about how to implement websockets with botman. Did I miss something ? Do you have any resource to share ? Tks !

**Comment by zamvar** [comment]
hi @rgr do you happen to find a solution or guide for this ?, im interested in doing the same, would appreciate any directions.

**Comment by filippotoso** [comment]
This is how you do it.

1. Download, configure and run [Laravel Websockets](https://beyondco.de/docs/laravel-websockets/getting-started/introduction) 
2. Integrate [Laravel Echo](https://laravel.com/docs/9.x/broadcasting#client-side-installation) in [Botman Web Widget](https://github.com/botman/web-widget) so that when it receives a message from the websocket server using Laravel Echo it displays it in the messages container.
3. Configure [Laravel for broadcasting](https://laravel.com/docs/9.x/broadcasting) through your Laravel Websockets instance.
4. When you need to originate a message, [broadcast an event ](https://laravel.com/docs/9.x/broadcasting#defining-broadcast-events) with the message content.

**Comment by rgr** [comment]
Well since I didn't know how to use websockets with flutter at that time I did the following : sending a transparent notification to the app using firebase (just a payload, no data display), this payload would activate a function that would send a request to the server. So it would seem it emanates from the server but it doesn't...

**Comment by zamvar** [comment]
Hi @rgr and @filippotoso i appreciate both of this approach ill try this over the weekend
Thanks!
