### ISSUE TITLE
Drivers loaded in Botman Provider but not used

### ISSUE THREAD

**Issue by jilenloa** [mpociot/botman#1236]
- BotMan Version: 2.6.1
- PHP Version: 7.3
- Messaging Service(s): custom (Twilio Whatsapp)
- Cache Driver: Laravel (file)

### Description:
matchesRequest method of loaded drivers never called. It's as if the driver is loaded but never used.

I had to update the app.php in config folder to correct this, I made the loading of the drivers happen before the routes are declared.

```
App\Providers\BotMan\DriverServiceProvider::class,
App\Providers\RouteServiceProvider::class,
```

### Steps To Reproduce:
Run the "bot new <name>" command
Load your drivers by updating the $drivers property in the Botman provider in app.
Serve
Then invoke the http://localhost:8000/botman endpoint via your bot or simulate using Postman (or any other http request utility)

**Comment by jlmasson** [comment]
Hi, I have the same problem here. @mpociot . I was trying to make a custom driver for a Whatsapp Business API Provider. I debugged it in the buildPayload method, I set the webhook url to the botman endpoint. Only the buildPayload method worked, and the others didn't work.

Also I entered in the source code of BotMan, and make some prints to log to see what was happening. I noticed that BotMan only takes in consideration the drivers that were loaded as a packages. For example, web driver and telegram driver.

So, I created a local package in order to load the custom driver.

I think that this is not the real solution, because, the file provided **App\Providers\BotMan\DriverServiceProvider::class**, should load this driver.

I followed all the steps in the documentation, and I found that the provider loaded, but after some time, the method **getMatchingDriver** in DriverManager.php didin't find the custom driver.

I logged the available drivers that was loading this method **getAvailableDrivers** and I saw that the custom driver never loaded, so the custom driver didn't match. However, when I logged in the buildPayload method of my custom driver, this method printed the content of the request.

**Comment by AvneetSingh27** [comment]
I want to transfer my chatbot conversation to real support agent(live conversation). So I thought of building a custom driver for the same
As I am new to this, I haven't made any custom driver. Can you help me out in doing so? @jlmasson @jilenloa @mpociot 
I have read the documentation but not able to decide how to start with it.

**Comment by legreco** [comment]
@jlmasson Did you find a solution for this problem?

**Comment by jilenloa** [comment]
> @jlmasson Did you find a solution for this problem?
The workaround I used at that time is in the description of my issue.

I had to update the app.php in config folder to correct this, I made the loading of the drivers happen before the routes are declared.

```
App\Providers\BotMan\DriverServiceProvider::class,
App\Providers\RouteServiceProvider::class,
```

**Comment by jilenloa** [comment]
> I want to transfer my chatbot conversation to real support agent(live conversation). So I thought of building a custom driver for the same As I am new to this, I haven't made any custom driver. Can you help me out in doing so? @jlmasson @jilenloa @mpociot I have read the documentation but not able to decide how to start with it.

Sorry for the delayed response. Ideally you need to extend HttpDriver. However, check this gist: https://gist.github.com/echr/d5141b0a3210462d32ed1fc3a621c371

**Comment by legreco** [comment]
@jilenloa your solutions works. But i wonder if it is the best solution.
![Whatsapp](https://user-images.githubusercontent.com/12883609/155055250-b59ea97b-8ac7-4dfb-b71f-ec42e433fddc.JPG)
I print some text in the buildpayload and the matchesRequest methods to see the flow of execution and it seems that these methods are executed twice.

**Comment by marteze** [comment]
> > @jlmasson Did you find a solution for this problem?
> > The workaround I used at that time is in the description of my issue.
> 
> I had to update the app.php in config folder to correct this, I made the loading of the drivers happen before the routes are declared.
> 
> ```
> App\Providers\BotMan\DriverServiceProvider::class,
> App\Providers\RouteServiceProvider::class,
> ```

Thank you very much!!! You did save me from hours trying understand what was i'm doing wrong in my code!!!!
