### ISSUE TITLE
Did any one Implemented live agent chat using Botman?? Custom Driver Implementation?

### ISSUE THREAD

**Issue by AvneetSingh27** [mpociot/botman#1275]
I am not able to figure out how to transfer the on going conversation to a real human so that human can answer those questions
I thought of writing my own custom driver for the same, but unable to do so. I am not able to decide how to start. I have read the documentation but not worth it.
Any suggestions?? Please help @mpociot @christophrumpel @feralheart

**Comment by filippotoso** [comment]
You can use a Middelware to sto Botman from answering when the user is in conversation with an operator (save this status in a database).

To implement the communication between user and operator, it depends on the driver. With something like Telegram and Facebook you can just use a middleware to save the user's messages in a database and use a notification system to make them appear in the operator chat (ie. using a websocket server). For the messages from the operator to the user, you just use the driver directly.

In the case of the webchat you need to implement something like Laravel Echo to receive the messages from the operator.

I know this will work because I have already implemented a similar solution.
