### ISSUE TITLE
Show user button selection as reply ?

### ISSUE THREAD

**Issue by smsalert-mobi** [mpociot/botman#1322]
Hello,
is there a way to show selected option as user reply in chat after he clicks on the conversation button ?
Now questions box disappears after user selects an option and bot gives a response, conversation can be tricky like this, users can forget what option did select.
Also is it possible to keep the buttons ?

Thanks.

**Comment by filippotoso** [comment]
Just "say()" what the user has selected as a confirmation text.

**Comment by smsalert-mobi** [comment]
say() is a bot originated message not user, so a conversation with buttons will be a monologue

**Comment by filippotoso** [comment]
The bot send a question with buttons.
The users clicks on a button.
The bot confirms the button clicked by the user with the `say()` method (something like "{value selected}, perfect!"). I use this solution in all my bots and the users are not confused.

**Comment by Asedol** [comment]
However, is there any way to make the selected response show up as the user's response?

**Comment by filippotoso** [comment]
> The bot confirms the button clicked by the user with the say() method (something like "{value selected}, perfect!"). I use this solution in all my bots and the users are not confused.

**Comment by axwell** [comment]
@filippotoso you always respond around the subject ? check other chat bots on the market... we do not need your workarounds.

**Comment by Asedol** [comment]
> > The bot confirms the button clicked by the user with the say() method (something like "{value selected}, perfect!"). I use this solution in all my bots and the users are not confused.

Unfortunately, this option does not suit me

**Comment by filippotoso** [comment]
This issue is only related to the web widget because is the only one where Botman has something to say about the UI.

For Telegram, Messenger, and so on you have only the solution suggested (i.e say()) because is the platform that dictates what is shown to the user after a click on a button.

So, for the web widget: do you need to show the button cliccked from within the widget? You can clone the repository and make the changes you need. That's the beauty of open source software.
