### ISSUE TITLE
custom driver  Not loaded

### ISSUE THREAD

**Issue by MohamedShetewy** [mpociot/botman#1341]
- BotMan Version: 2
- PHP Version: 7.3
- Cache Driver: SymfonyCache

-I not use Laravel
 
-i want to create custom driver whatsapp but not load i define i file namespace and in index do 

use BotMan\Drivers\Whatsapp\WhatsappDriver;
DriverManager::loadDriver(WhatsappDriver::class);

$adapter = new FilesystemAdapter();

$botman = BotManFactory::create($config, new SymfonyCache($adapter));

and not happen anything where autoload not load driver 
- how solve this problem ?

**Comment by filippotoso** [comment]
If it's a problem with the class autoload it's not a Botman issue but a PHP issue.

Implement you own autoloader as per PHP documentation. 

https://www.php.net/manual/en/language.oop5.autoload.php

Otherwise, just include the required files and add the required use clauses in the file header.

https://www.php.net/include
https://www.php.net/manual/en/language.namespaces.importing.php
