### ISSUE TITLE
[Middleware] Call method handle only if the isMessageMatching return true

### ISSUE THREAD

**Issue by SergiX44** [mpociot/botman#137]
It makes no sense to call the handle method for each command even if the method isMessageMatching returns false. For example, i've made a middleware for add to the message extras some infomations, and the same information are added to the message extras for each command that the bot hears, also if they are not matching the message regex.

**Comment by mpociot** [comment]
Hey,

This is actually a feature. Imagine you want to send the incoming middleware text to a third party service and after that happens, validate a special extra property on the message. 

Or you could ignore the regular expression completely and make sure that your message comes from a specific user. 

That's why the middleware handle method is called nonetheless.

**Comment by SergiX44** [comment]
Yeah, you right, but if in a middleware I try to retrieve some user informations from a database doing something like this:
```
$user = User::where('telegram_id', $message->getUser())
				->orWhere('facebook_id', $message->getUser())
				->first();
$message->addExtras('user', $user);
```
If I register 10 commands, the same query will be executed 10 times.
I cannot even avoid repetition in this way:

```
if (is_null($message->getExtras('user'))) {
    $user = User::where('telegram_id', $message->getUser())
				->orWhere('facebook_id', $message->getUser())
				->first();
    $message->addExtras('user', $user);
}
```
Because it's seems that $message is every times a new instance.

I think that should be added a way to execute a method of the middleware only when isMessageMatching is true, to simplify checks inside the commands.
