### ISSUE TITLE
Is this package suite still maintained?

### ISSUE THREAD

**Issue by Jnesselr** [mpociot/botman#1392]
It looks like @mpociot no longer is the main maintainer and @filippotoso has made some commits, but I don't know if that means they took over or not. I tried looking at the forum, but it doesn't look like it's been updated since 2018 and I can't read any posts without getting a 500. The readme points to @mpociot's pages for funding it looks like. The slack driver basically can't be installed at the moment due to outdated versions.

This seems like a really cool project, I'm hopeful it's still lingering on but I didn't want to invest too much time into it unless I knew it was maintained and PRs might get accepted.

**Comment by filippotoso** [comment]
I use Botman daily and I try to maintain it working with the latest version of Laravel. I don't have much time to maintain the third party drivers because they age very quickly due to API changes and I use just the main ones (ie. Telegram and Facebook).

If you want to contribute to the Slack one, make a PR and I'll approve it.
