### ISSUE TITLE
Is this project abandoned? 

### ISSUE THREAD

**Issue by ftrotter** [mpociot/botman#1409]
I have been through the source code and documentation for all three of the relevant projects: botman, botman studio and botman slack. 

All three indicate a preference for the use of the long-deprecated Slack RTM method. When this broke, the following tickets were created and ignored: 

https://github.com/botman/driver-slack/issues/55
https://github.com/botman/driver-slack/issues/69

I believe these both have to do with the fact that the RTM API is not support. 

The current version of botman slack still attempts to use the RTM API. Or at least it is named that way. It might be possible to get the botman studio version to use the "Slack" driver (which might still work) instead of the SlackRTM driver. 

The project documentation is outdated and frozen, the code is really old. The likelyhood that this project is alive seems very low. 

Your mileage may very, but even if you are not using Slack, I think the project is just not maintained. So when your Chat API of choice inevitably changes.. well.. things coded in Botman will no longer work. Which sort of negates the purpose of the project, which is to have one codebase that can make the same chatbot work on different platforms. 

Again, my apologies if this is interpreted as an attack... but I have to warn people not to make the same mistake investment in the library that I did.

**Comment by filippotoso** [comment]
First of all, Botman is not abandoned. I still keep it up to date with new version of Laravel, fix small bugs as I find them, merge PRs if they made sense and so on.

I use Botman for work daily, I have multiple multitenant platforms with tens of bots running in the cloud and on premise. I have paying client that use those bots for a great number of different tasks.

That said, I do not maintain Botman Studio as, from my point of view, it doesn't make sense. You can setup a new Laravel application with Botman in 5 minutes following these steps: 

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604

The beauty of this approach is that you undestand how Botman works (how it receive the messages, how it processes, all the required components, and so on) instead of relaying on the "magic" under the Studio hood.

Morover I try to maintain and improve the drivers I use, nameply Facebook and Telegram. I also developed multiple proprietary drivers such as RocketChat (years ago), Vonage WhatsApp, Vonage Voice (I have bots that answer the phone) and a highly complex webchat with websocket support for one to one operator / customer live interactions.

I cannot spend time maitaining drivers that I don't use because I don't have the time.

But that's the beauty of open source software, anyone can roll up their sleeve and work on them.

If you need an update version of the Slack driver, check the official documentation, implement it and submit it as a PR to the Slack Driver repository. I'll take the time to testit and approved when you'll do it. Is that simple.

**Comment by ftrotter** [comment]
With respect, your documentation says that it supports slack, but just admitted that you don't support slack. Your documentation says that it supports botman studio, but you just admitted that you don't support that either. The stated goal of your project is to be cross platform, and slack is clearly a platform that would be included in such a goal.  

You are saying that the project is not abandoned, while listing out which features you have abandoned, without documenting that they are abandoned. 

I will see if I can get the slack driver to work using the method you linked to. That should allow me to use the "slack" but not "slackRTM" driver. If that works, I will submit a pull request to modify the documentation to use those instructions. If I cannot I will submit request to modify the documentation to note that the slack support does not work. 

-FT

**Comment by filippotoso** [comment]
You are talking about "your documentation" but you should have said "Botman documentation".

I'm not the original creator of Botman. I do not own botman.io nor I have access to it to make any change to its content.

**Comment by ftrotter** [comment]
Hmm.. it sounds like you are as much a victim here as I am. 
I appreciate the work you are doing to keep the project alive. 

I have submitted pull requests to the botman studio, and the documentation. 
Both of these pull requests assume that the support that you provide is the only support available. 

If it is true that you are the only support available, then I propose that you fork the project into a new repo that you can fully own. 

Even if I could wave a magic wand and fix the Slack integration and remove the RTM code and replace it with new code that works with slacks current APIs... unless the documentation can be updated.. then new users of this project will have the same frustrating experience that I had. 

While I certainly appreciate your work keeping the project alive, unless the documentation and the code match up, then the project will continue to be on life support. This is not fair to you as a maintainer or me as a contributor/user... or to anyone else who uses the project. I know suggesting forks is a kind of violence in open source... but I think this is warranted. 

Happy to be proven wrong by the project owners. Will give this issue a week or so to see if there is a meaningful response.. but if there is not.. well then something needs to be done. I do not have much of a budget, only a few hundred bucks for this. But I am willing to put a little money where my mouth is to spend that budget to sponsor the work to fork the project and to fix the Slack API if that would be helpful.

**Comment by nicodemuz** [comment]
@mpociot You should make @filippotoso the maintainer of all the BotMan repositories.
