### ISSUE TITLE
Cannot serialize closure with Symfony cache

### ISSUE THREAD

**Issue by gromez** [mpociot/botman#156]
Hey, me again :)

I'm not using Laravel, I'm using Slim Framework, and I'm using botman with composer.
I think there is another issue with the SymfonyCache adapter. I tried with the filesystem and redis cache engine, but always the same problem.

I tried with the `PizzaConversation` example, here is the error: `Serialization of 'Closure' is not allowed`

```
$cache = new \Symfony\Component\Cache\Adapter\FilesystemAdapter();
$botman = \Mpociot\BotMan\BotManFactory::create($settings, new \Mpociot\BotMan\Cache\SymfonyCache($cache));

$botman->hears('/pizza', function (BotMan $bot) {
    $bot->startConversation(new PizzaConversation);
});

$botman->listen();
```

Tried with latest botman release and `dev-master` branch, same result.

**Comment by mpociot** [comment]
Hey,

I changed the way the serialization of conversation objects work. Please try it again with the latest `dev-master` version.

**Comment by gromez** [comment]
Great, works fine :)

Thank you :+1:

**Comment by mpociot** [comment]
Great! Please use dev master in the meantime. I have two more features I want to get done before releasing 1.4.0 :)

**Comment by mpociot** [comment]
I have to reopen this issue and roll back the commit.
My modification allowed the Symfony Cache driver, but it also disabled the ability to use BotMan within Queued Jobs.

Right now I only have two possible solutions:
- Enable Symfony Cache, but loose the ability to use the bot inside queues (which is bad because most messaging drivers have a response time limit of 3-15 seconds).
- Disable Symfony Cache

If someone wants to look at this issue, any help is greatly appreciated.
The problem is that I need to be able to serialize / unserialize the complete BotMan object with the driver + cache loaded, so it can be used in a queue or after getting loaded from the cache.

**Comment by mpociot** [comment]
This is now resolved, as you can use the `ShouldQueue` interface on queuable conversations.
