### ISSUE TITLE
Skype group url

### ISSUE THREAD

**Issue by kiwina** [mpociot/botman#187]
Hi noticed that setting https://skype.botframework.com as default if no serviceUrl is available 
dosn't work with say() on group chat.
if i change it to https://smba.trafficmanager.net/apis/ (mind the ending slash) then it works fine.
I wander if it's like that for everyone?

**Comment by mpociot** [comment]
Is this documented somewhere from Microsoft?

**Comment by thedotedge** [comment]
I have the same problem with say() on individual chat as well. The problem is that serviceUrl can't be hardcoded anymore (ref. https://github.com/Microsoft/BotBuilder/issues/2005 for example).
Correct serviceUrl can be obtained from payload from original response in `hears`:

```
Symfony\Component\HttpFoundation\ParameterBag::__set_state(array(
   'parameters' =>
  array (
    'text' => 'hello',
    'type' => 'message',
    'timestamp' => '2017-02-05T09:41:40.151Z',
    'id' => '1486287700146',
    'channelId' => 'skype',
    'serviceUrl' => 'https://smba.trafficmanager.net/apis/',
    'from' => 
...
```

The problem is that when we call `say()` there seems to be no way to pass `payload` to https://github.com/mpociot/botman/blob/1.3.0/src/Mpociot/BotMan/Drivers/BotFrameworkDriver.php#L165 or am I missing something?

**Comment by mpociot** [comment]
Okay. So the problem only occurs when you try to originate messages from your bot to your users. 

Responding to incoming requests should work just fine since the payload is set in this case. 

So when originating a message, we need to add an additional field for the bot framework driver that sets the service URL , right?

**Comment by thedotedge** [comment]
That seems to be correct as per https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html:
```
NOTE: Even though ServiceUrl values may seem stable bots should not rely on that and instead always use the ServiceUrl value
```

Should it be on bot framework driver level or on Question level in case when multiple URLs would be in use simultaneously?

**Comment by mpociot** [comment]
You can now pass the `serviceUrl` to the `say` method using additional parameters.

```php
$botman->say('message', 'recipient', BotFrameworkDriver::class, [
    'serviceUrl' => 'https://smba.trafficmanager.net/apis/'
]);
```

**Comment by thedotedge** [comment]
Most impressive responsiveness 🥇

**Comment by kiwina** [comment]
Super
