### ISSUE TITLE
Bot doesn't hear other bots (slack)

### ISSUE THREAD

**Issue by TondaRuzicka** [mpociot/botman#222]
Hi,

when using $bot->hears(), it doesn't register other bots (RTM or webhooks). How can this be fixed?

Thanks

**Comment by mpociot** [comment]
Hmm...this is currently on purpose because especially Slack sends back the bot messages.
So for example, if you have something like this:

```php

$botman->hears('hello', function($bot) {
    $bot->reply('hello');
});
```

This would result in an infinite loop, because BotMan would always listen to itself over and over again.

That's why each messaging driver has a `isBot` method to determine if the message is sent from a bot and it gets ignored in that case:

https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Drivers/SlackRTMDriver.php#L86-L89

https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Drivers/SlackDriver.php#L119-L122

We would need to gather the own bot id first, and only ignore messages that have the same bot id.

**Comment by Kcharle** [comment]
@mpociot I'm trying to do something similar 

I have my server deploying software (forge.laravel.com) sending a notification to a channel in slack where my botman lives, i have the botman setup to hear "deployed some fresh code!" and respond back saying "feeling fresh!" but it doesn't detect the text when the notification is sent to the channel by the forge app, it will however detect it if I type it as my slack user.

![image](https://user-images.githubusercontent.com/4724339/28197443-f3c20060-6824-11e7-82ef-b89b838903e5.png)
