### ISSUE TITLE
Symfony, Doctrine.. serialize unserialize issue

### ISSUE THREAD

**Issue by jayesbe** [mpociot/botman#403]
- BotMan Version: 1.5.6
- PHP Version: 7.1
- Messaging Service(s): Facebook Messenger
- Cache Driver: Redis

### Description:
I am trying to use Doctrine after receiving answer. In order to save some information to a database.
I supplied a Doctrine Entity Manager to the Conversation class as well as tried passing in the Event Dispatcher to the Conversation class.  When I do so, there is a serialize / unserialize exception occurring such as 

```
2017-05-28 20:31:56] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Instances of Aws\S3\S3Client cannot be serialized" at /var/www/app/vendor/aws/aws-sdk-php/src/AwsClient.php line 230 {"exception":"[object] (RuntimeException(code: 0): Instances of Aws\\S3\\S3Client cannot be serialized at /var/www/app/vendor/aws/aws-sdk-php/src/AwsClient.php:230)"} []

```

If I remove Event Dispatcher and just try Doctrine Entity Manager.. I get the following exception

```
[2017-05-28 10:35:45] request.CRITICAL: Uncaught PHP Exception PDOException: "You cannot serialize or unserialize PDO instances" at /var/www/app/vendor/opis/closure/lib/SerializableClosure.php line 194 {"exception":"[object] (PDOException(code: 0): You cannot serialize or unserialize PDO instances at /var/www/app/vendor/opis/closure/lib/SerializableClosure.php:194)"} []

```

Totally unsure of how I can save info to a DB after hearing an answer.

The following code is the implementation using Event Dispatcher.

```
	public function askQuestions()
	{
		$convo = $this;
		
		$this->ask('What are some things you like?', function(Answer $answer) use ($convo) { 
			try {
				$event = new GenericEvent($convo);
				$event->setArgument('answer', $answer);
				$convo->getEventDispatcher()->dispatch('user.onboarding', $event);
			}
			catch (\Exception $e) {
				$this->say("Unfortunately we could not save your profile, we'll have to try again. I apologise for the inconvenience");
			}
		});
	}
```

**Comment by mpociot** [comment]
I'll need to look more into the specific problem, but just to explain to you why this happens:

In order to "remember" a conversation state, BotMan needs to serialize the conversation class and the closure that needs to be executed when the user enters an answer. 
This is pretty essential because otherwise BotMan wouldn't know if you want to pick up an existing conversation or not. 

Does your conversation class have special properties that contain unserializable objects? Like the S3 client?

**Comment by jayesbe** [comment]
@mpociot  nope. My guess is its linking to all the objects that are hooked into the Symfony service container.  the S3 client is the very first object in the container alphabetically. (AwsS3) 

So would you say its the Conversation itself?  or the Answer closure?

As you can see from my example above.. the Event Dispatcher is associated to the Conversation itself.

So when I create the Conversation object and ass that to the startConversation method, I have already passed into it an Event Dispatcher (or Doctrine Registry) instance.

**Comment by mpociot** [comment]
Yeah the problem might be, that it's trying to serialize the closure and therefore also this line:

`$event = new GenericEvent($convo);`

The only way to get rid of serialization is to start BotMan as a PHP process (it's not yet released). This way the conversations don't need to be cached/seralized and will only be stored in memory in an array.

I personally do not really like this approach, because it makes deployment a bit harder. You would then need to restart the BotMan listener process and running conversations might just end. 
Anyway - it'll be available soon. 

The call would then look something like this:

```php
/**
 * This file spawns the socket process.
 */
use React\EventLoop\Factory;

$loop = Factory::create();
$botman = BotManFactory::createForSocket($config, $loop);

$botman->hears('foo', function($bot) {
    $bot->startConversation(new ExampleConversation());
});

$loop->run();
```

This would need to be somewhere in your HTTP controller that handles incoming webhooks.
```php
/**
 * Pass the request data in your webhook to the socket
 */
BotManFactory.:passReqeustToSocket();
```

Let me know if you want to give the socket approach a try. I have it in a separate branch on my local machine.

**Comment by jayesbe** [comment]
Instead of creating the event inside the answer closure.. I could create it outside and pass it in.. but that may just lead to the same issue.. id probably bet on it.

As for the background process. I like the approach better because I think it would lead to a more resilient and performant bot.. even though it has to be restarted on deployment.  I dont like that it stores everything in memory.. can't it continue to use redis ?

will give this a try though

**Comment by mpociot** [comment]
Well if it stores the conversation in redis, we would still end up with the need to serialize everything.
I don't see another way of dealing with this. If you want to cache the closure/conversation in a file/database/whatever it needs to be serialized.

**Comment by jayesbe** [comment]
Ah ok. So the Conversation object itself is being serialized?

**Comment by mpociot** [comment]
Yes, because you could refer to conversation properties inside your questions.

For example:

```php
class DummyConversation extends Conversation {

	private $name;
	private $age;

	public function run()
	{
		$this->ask('What is your name?', function($answer) {
			$this->name = $answer->getValue();
			$this->askAge();
		});
	}

	public function askAge()
	{
		$this->ask('Hello '.$this->name.'. What is your age?', function($answer) {
			$this->age = $answer->getValue();
		});
	}

}
```

**Comment by jayesbe** [comment]
Which makes sense why I was getting those errors now because both doctrine and event dispatcher are being set as properties. So that means Conversation objects can only contain serializable props. 

There needs to be some type of proxy method or something that allows the bot to call outside. hmm..

**Comment by jayesbe** [comment]
@mpociot  I see a protected botman object inside the Conversation object.  Is the botman object serialized along with the conversation object?

**Comment by mpociot** [comment]
No:
https://github.com/mpociot/botman/blob/master/src/Conversation.php#L185
https://github.com/mpociot/botman/blob/master/src/Traits/HandlesConversations.php#L216

**Comment by jayesbe** [comment]
damn I thought I had a solution using ShouldQueue interface.. created an event dispatcher wrapper that implements shouldqueue .. 

still fails..

```

$eventDispatcher = new EventDispatcher();
$eventDispatcher->setEventDispatcher($controller->get('event_dispatcher'));
$convo->setEventDispatcher($eventDispatcher);
$bot->startConversation($convo);

```

the new EventDispatcher object above is a wrapper around the symfony event dispatcher but implements ShouldQueue .. some how it still ends up trying to serialize the wrapped eventDispatcher property. 

```

<?php 
namespace AppBundle\Botman;

use Mpociot\BotMan\Interfaces\ShouldQueue;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\Event;

class EventDispatcher implements ShouldQueue
{
	private $eventDispatcher;
	
	public function setEventDispatcher(EventDispatcherInterface $eventDispatcher)
	{
		$this->eventDispatcher = $eventDispatcher;
	}
	
	public function dispatch($eventName, Event $event) 
	{
		$this->eventDispatcher->dispatch($eventName, $event);
	}
}
```

**Comment by TheWildHorse** [comment]
Here is how I solved the problem: https://rinkovec.com/using-botman-symfony-service-container/

**Comment by vesper8** [comment]
@TheWildHorse thanks for sharing your solution.. could you give any indication of how to adapt this to the Laravel framework? I tried applying your solution but it says `Symfony\Component\DependencyInjection\ContainerAwareTrait` doesn't exist

I suspect the rest of the logic might not be so plug-and-play either

Would appreciate some help, am stuck on the same issue

**Comment by TheWildHorse** [comment]
@vesper8 Since this framework is built upon Laravel I am guessing you are doing something out of the norm to get this error. Can you post some info on the error you get and the object that is causing this issue?

**Comment by vesper8** [comment]
I'm not sure what I'm doing wrong.. it just says 

```
Trait 'Symfony\Component\DependencyInjection\ContainerAwareTrait' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Trait 'Symfony\\Component\\DependencyInjection\\ContainerAwareTrait' not found at /Volumes/DEV/mydomain/modules/maddons/chatbot/src/Traits/ContainerAwareConversationTrait.php:10)
```

I do see two references to `use Symfony\Component\DependencyInjection\ContainerAwareTrait;` inside my vendor folder, but I do not see a file containing the trait itself so maybe this dependency just isn't loaded by default with Laravel?

Another thing is that since I don't use services.yml in order to inject containers like you showed in your example, I simple created a _baseConversation class which extends Botman's Conversation class and am adding a `use ContainerAwareConversationTrait;` in there

I'm not sure if that could be the problem, it seems more likely that I just don't have the ContainerAwareTrait in my dependencies

**Comment by TheWildHorse** [comment]
@vesper8 My solution won't work for you, it is tailored for Symfony specifically. Can you send me the info about your initial issue so I can try to help that way?

**Comment by vesper8** [comment]
I just made an issue an hour ago detailing it in as much details as I could

Can you have a look and let me know your thoughts? Much appreciated!

Here is the issue https://github.com/botman/botman/issues/1007

Thanks
