### ISSUE TITLE
Is there a sample code for API.AI

### ISSUE THREAD

**Issue by ranrinc** [mpociot/botman#414]
Hi there,

trying to create my botman using API.AI and have not being able to make it work. Is there a guide or sample on how to connect it.

`use Mpociot\BotMan\Middleware\ApiAi;

$botman->hears('my_api_action', function($bot) {
	// The incoming message matched the "my_api_action" on API.ai
	// Retrieve API.ai information:
	$extras = $bot->getMessage()->getExtras();
	$apiReply = $extras['apiReply'];
	$apiAction = $extras['apiAction'];
	$apiIntent = $extras['apiIntent'];

	$bot->reply("this is my reply");
})->middleware(ApiAi::create('your-api-ai-token')->listenForAction());`

i did put the code in and add Client Access Token and did try to figure it out what need to be input on my_api_action?

Any help?

- BotMan Version: 1.5.7
- PHP Version: 5.6.30
- Messaging Service(s): Telegram
- Cache Driver: n/a

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey @ranrinc , just tested.
For me it works perfectly when I remove the `->listenForAction()`.
Without it, every message that matches the `hears` will be send to API.ai and you will get some extra information.

As far as I know the `->listenForAction()` is a feature so that only certain actions from API.ai will get triggered. But I am not completely sure right now.

**Comment by ranrinc** [comment]
@christophrumpel 

Thank you for the reply. Still need more advice if you dont mind.
`$botman->hears('my_api_action', function($bot) {`

What is my_api_action? I mean what do I need to fill in that spot?

`})->middleware(ApiAi::create('your-api-ai-token')->listenForAction());`

What is "your-api-ai-token"? is this client access or developer access token?

So the last line I should wrote like this in order it to work?

`})->middleware(ApiAi::create('your-api-ai-token'));`

Sorry for all this stupid question since I'm really a nubie who would like to have the bot run.

**Comment by christophrumpel** [comment]
Ah sry, I wasn't clear enough. Now I also got what the example from the doc means.

So when you use the exact code from the docs with `listenForAction()` then you will write the name of the API.ai action inside the `hears` method. This is why it says `my_api_action`. Inside API.ai you can define actions for certain intents. For example I have an intent for greetings and in api.ai I have some example sentences like: hello, hi there, hell you etc. For all these examples I API.ai can trigger an action. This is just a string you can define.

So for everything the user writes in the bot, BotMan will send that to API.ai and check if the returned action is the one that you mentioned in the `hears`.

So for the token you can use both tokens from API.ai as far as I know, but I would use the client one, because this one you can refresh.

Did this help?

**Comment by ranrinc** [comment]
@christophrumpel 

Heemm its seem that the system did not give any answer instead it keep on saying "this is my reply"

Again sorry for being nubie... so I replace `my_api_action` with `hello there` and the replay is `this is my reply` 

So I guess the API didn't get called? Confused... Is there a code or sample that I can copy or see? Again sorry for this

**Comment by christophrumpel** [comment]
Hey, I know it gets confusing at the beginning. Here is my example:

```php

$botman->hears('greeting_action', function($bot) {
            // The incoming message matched the "my_api_action" on API.ai
            // Retrieve API.ai information:
            $extras = $bot->getMessage()->getExtras();
            $apiReply = $extras['apiReply'];
            $apiAction = $extras['apiAction'];
            $apiIntent = $extras['apiIntent'];

            $bot->reply("this is my reply: " . json_encode($extras));
        })->middleware(ApiAi::create('your-api-ai-token')->listenForAction());
```

Here I am listening for the `greeting_action` which I created in API.ai. So for every user message, Botman is checking if API.ai is sending back the matched action. If it is matched, the reply "this is my reply..." will be send as an answer. In my example I am also adding the extra information API.ai is sending back, like the action name, the intent etc. So when you get this reply, it means everything worked out. There is no full example as far as I know.

**Comment by ranrinc** [comment]
@christophrumpel 

Got it.... many thanks.

**Comment by christophrumpel** [comment]
Perfect!If you need anything else you can always join as the Slack channel as well. 👍

**Comment by ranrinc** [comment]
@christophrumpel 

What do you mean by Slack Channel? Or you mean I can connect the bot to Slack too? Sorry again I'm not that good...

**Comment by christophrumpel** [comment]
No no, I meant there is a BotMan Slack channel where developers and BotMan Fans hang out and chat about BotMan. So if you have the chat program Slack installed on your machine, then you can come there to talk. On botman.io is also a link the top bar for the Slack channel. https://botman.io

**Comment by ranrinc** [comment]
@christophrumpel 

Alright... will do that..
BTW may I replace `$botman->hears('Small-Talk', function($bot) {` with `$botman->fallback('Small-Talk', function($bot) {`

Would like to have the bot to listen to others specific comment and use API.AI as the last resource if it couldn't find any specific
